name: Build & Test

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
        ocaml-compiler:
          - "4.14.x"
          - "5.4.x"

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout tree
      uses: actions/checkout@v4

    - name: Set-up OCaml
      uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}

    - name: Install OCaml deps
      run: opam install . --deps-only --with-test

    - name: Build
      run: opam exec -- dune build

    - name: Test
      run: opam exec -- dune runtest

  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: "5.4.x"

      - name: Lint fmt
        uses: ocaml/setup-ocaml/lint-fmt@v3
